Applying terraform format to all files
GoogleCloudPlatform/terraform-splunk-log-export pull request #18
Opened 2022-11-16 23:46 UTC by Lakhtenkov-iv

2022-11-18 23:30 UTC, Lakhtenkov-iv commented
Hi @rarsan, @npredey.
I want to contribute feature for KMS encrypted tokens and token from Secretes.
The branch is huge and it is here: https://github.com/Lakhtenkov-iv/terraform-splunk-log-export/pull/4
In order to simplify PR review process I spitted it in to 3 PRs:
1. Fix terraform format
2.  Add terraform-docs support
3. Actual KMS and Secrets feature

Is PR is number 1 from the list. Could you please review and merge.

2022-11-20 00:29 UTC, rarsan commented
Thank you @Lakhtenkov-iv for contributing this. I see you already signed the CLA.

I appreciate you breaking this down into 3 PRs. I will review all by Mon or Tue. Thanks.

2022-11-22 22:53 UTC, rarsan requested changes
Thanks for your patience. Looks good! Some minor comments below. Please see note re 2 required variables that were accidentally removed.

With respect to the workflow yaml file, I appreciate you adding that. Do we need to add any usage instructions?

2022-11-22 22:53 UTC, rarsan commented on main.tf
> -  dataflow_pubsub_template_gcs_path = "gs://dataflow-templates/${var.dataflow_template_version}/Cloud_PubSub_to_Cloud_PubSub"
This variable is used in the replay pipeline included in `replay.tf`. The replay pipeline is only deployed to recover undelivered messages as described in this [solution guide](https://cloud.google.com/architecture/deploying-production-ready-log-exports-to-splunk-using-dataflow#handling_delivery_failures). Therefore it's commented out by default in the `replay.tf` file. There are probably better ways to do this, but for now we probably add lint warning ignore around this.

2022-11-22 22:53 UTC, rarsan commented on main.tf
> -  organization_log_sink_name = "${var.dataflow_job_name}-organization-log-sink"
Same with this variable which is used in a commented out resource `organization_log_sink`. Let's add tflint-ignore for now? We can add a terraform variable in subsequent PR to conditionally control creation of the org log sink (in addition to new organization_id TF variable).

2022-11-22 22:53 UTC, rarsan commented on versions.tf
> +terraform {
Thanks for adding the providers and versions files.
I don't think I've personally tested these older provider versions though.
Has this been tested with these versions? For example, `random` version below is about 5 yrs old.

2022-11-23 22:29 UTC, Lakhtenkov-iv commented on main.tf
> -  dataflow_pubsub_template_gcs_path = "gs://dataflow-templates/${var.dataflow_template_version}/Cloud_PubSub_to_Cloud_PubSub"
Sorry I didn't get the point that I need to uncomment the code to deploy. I have brought back variable.

2022-11-23 22:29 UTC, Lakhtenkov-iv commented on main.tf
> -  organization_log_sink_name = "${var.dataflow_job_name}-organization-log-sink"
Fixed as well.

2022-11-23 23:37 UTC, Lakhtenkov-iv commented on versions.tf
> +terraform {
Yes, you are right we need to bump up all the 3: `terraform`, `google` and `random` provider. I will test. Please don't merge

2022-11-24 00:00 UTC, Lakhtenkov-iv commented on versions.tf
> +terraform {
Now it is good, I've tested with minimal versions that is defined.

2022-11-30 10:56 UTC, Lakhtenkov-iv commented
Hi @rarsan. Any feedback on this PR?

2022-11-30 16:44 UTC, merged

2022-11-30 16:45 UTC, rarsan commented
Thanks for the fixes! PR merged.