Add kms and secret token types
GoogleCloudPlatform/terraform-splunk-log-export pull request #20
Opened 2022-11-18 23:37 UTC by Lakhtenkov-iv

This PR is adding ability to use following HEC token types:
- KMS
- SECRET_MANAGER

Other improvements:
- Added exclude to log sink to prevent infinite loops

-[] Merge after #18 
-[] Merge after #19

2022-11-23 19:33 UTC, rarsan reviewed
LGTM! We can merge this as soon as PR #18 and #19 are closed.

2022-12-01 17:44 UTC, rarsan commented on README.md
> +| <a name="input_splunk_hec_token_encription_key"></a> [splunk_hec_token_encription_key](#input_splunk_hec_token_encription_key) | (Optional) The Cloud KMS key to decrypt the HEC token string. Requir
Minor typo with encryption word.
While we're at it, let's rename this variable to `splunk_hec_token_kms_encryption_key` to be more clear and inline with template parameter tokenKMSEncryptionKey, even though it's bit more verbose.

2022-12-01 18:00 UTC, rarsan commented on permissions.tf
> +resource "google_secret_manager_secret_iam_binding" "dataflow_worker_role_read_secrets" {
minor nitpick: let's rename resource to `dataflow_worker_secret_access` to be consistent with other bindings like `dataflow_worker_bucket_access`

2022-12-01 18:39 UTC, rarsan commented on permissions.tf
> +  var.dataflow_worker_service_account == "") ? 1 : 0
I don't think we need the condition around `var.dataflow_worker_service_account`. Why is this restricted to only the case where dataflow service account not provided (i.e. only for Compute Engine default service account)?

The job will fail without the secret read permission added to`local.dataflow_worker_service_account` whether it's user-defined or default Compute Engine service account. We should use`iam_member` resource though in case there are other secret accessors pre-defined (most likely).

I think we should add a note in the README about this TF module potentially adding permissions to CE default service account to access secret (same for kms token).

2022-12-01 22:19 UTC, Lakhtenkov-iv commented on README.md
> +| <a name="input_splunk_hec_token_encription_key"></a> [splunk_hec_token_encription_key](#input_splunk_hec_token_encription_key) | (Optional) The Cloud KMS key to decrypt the HEC token string. Requir
Sure, thanks for attentiveness. Fixed.

2022-12-01 22:22 UTC, Lakhtenkov-iv commented on permissions.tf
> +resource "google_secret_manager_secret_iam_binding" "dataflow_worker_role_read_secrets" {
Make sense. Done.

2022-12-01 22:33 UTC, Lakhtenkov-iv commented on variables.tf
> +variable "splunk_hec_token_source" {
Not a problem. I added. But by the way that is not yaml.

2022-12-02 17:35 UTC, rarsan commented on variables.tf
> +variable "splunk_hec_token_source" {
Great point :)
I'm ok renaming it to something like `sample.tfvars` - we can do it in this PR or subsequent PR. LMK.

2022-12-02 17:44 UTC, rarsan commented on variables.yaml
> +splunk_hec_token_encription_key = ""
Minor typo `splunk_hec_token_kms_encryption_key`

2022-12-02 17:54 UTC, rarsan commented on permissions.tf
> +  var.dataflow_worker_service_account == "") ? 1 : 0
Thx for adding README warning.
Re 2 modes of work: that sounds great. I think we can make the default mode equivalent to existing behavior (module manages IAM permissions). We can discuss more in separate PR.

2022-12-02 18:01 UTC, Lakhtenkov-iv commented on variables.yaml
> +splunk_hec_token_encription_key = ""
Fixed

2022-12-02 20:21 UTC, rarsan requested changes
I've tested this PR locally. One suggested edit in `main.tf` to prevent a race condition (I encountered when using secret). 2 minor open comments below.

2022-12-02 20:21 UTC, rarsan commented on permissions.tf
> +  # If dataflow service account provided than appropriate bindings should be done outside of the module
I think we can remove this comment

2022-12-02 20:21 UTC, rarsan commented on permissions.tf
> +  # If dataflow service account provided than appropriate bindings should be done outside of the module
I think we can remove this comment.

2022-12-02 22:44 UTC, Lakhtenkov-iv commented on permissions.tf
> +  # If dataflow service account provided than appropriate bindings should be done outside of the module
Thanks, removed.

2022-12-02 22:44 UTC, Lakhtenkov-iv commented on permissions.tf
> +  # If dataflow service account provided than appropriate bindings should be done outside of the module
Removed.

2022-12-02 22:53 UTC, merged