network.tf file to create networking resources for Splunk export
GoogleCloudPlatform/terraform-splunk-log-export pull request #5
Opened 2021-04-27 17:35 UTC by npredey

* Also ran `terraform fmt` to clean up files

2021-04-28 22:07 UTC, rarsan requested changes
Thank you for this contribution!
Looks great, a couple of comments below. 
Possible to remove whitespace changes to preserve history?

2021-04-28 22:22 UTC, npredey commented on network.tf
> +  min_ports_per_vm                   = 1024
This is a good call out. I will change this to 128.

2021-04-28 22:23 UTC, npredey commented on network.tf
> +  ip_cidr_range            = var.primary_subnet_cidr
I'll add it in and then create that range as the default.

2021-04-28 22:25 UTC, npredey commented
> Thank you for this contribution!
> Looks great, a couple of comments below.
> Possible to remove whitespace changes to preserve history?

I was so in the mode of running `terraform fmt` that I committed it without realizing. I can look to revert that.

2021-04-29 22:38 UTC, rarsan commented on pipeline.tf
> +  network = var.create_netowork == true ? google_compute_network.splunk_export.id : var.network
just noticed typo with var name.

2021-04-29 22:43 UTC, rarsan requested changes
Looks good. Mind adding changes in the README? Particularly new user-facing variables.
Sorry forgot to mention that last time.
Also there's a simple variables placeholder file `variables.yaml` that needs to be updated with these new vars. It's made available for end-users to seed a new user-specific `terraform.tfvars` as described in README setup section.

2021-04-30 20:25 UTC, rarsan approved these changes

2021-04-30 20:25 UTC, merged